services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - app_network
    expose:
      - "8000"
    restart: unless-stopped
    init: true

  nginx:
    image: nginx
    depends_on:
          - backend
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    networks:
      - app_network
    ports:
      - "5000:5000"
    restart: unless-stopped
    init: true

networks:
  app_network:
    name: app_network
    driver: bridge
